package com.example.workmanagement.domain.review.enums;

public enum ReviewHistoryActionType {
    REVIEW_CREATED,
    REVIEW_RESUBMITTED,
    REVIEW_APPROVED,
    REVIEW_REJECTED,
    REVIEW_CANCELLED,
    REFERENCE_ASSIGNED,
    REFERENCE_REMOVED,
    ADDITIONAL_REVIEWER_ASSIGNED,
    ADDITIONAL_REVIEWER_REMOVED,
    ATTACHMENT_ADDED,
    ATTACHMENT_REMOVED,
    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED
}
